horaro\Library\Entity\Config:
  type: entity
  table: config

  id:
    keyname:
      type: string

  fields:
    value:
      type: text

horaro\Library\Entity\User:
  type: entity
  table: users
  repositoryClass: horaro\Library\Repository\UserRepository

  id:
    id:
      type: integer
      options: { unsigned: true }
      generator: { strategy: AUTO }

  fields:
    login:
      type: string
      length: 100
    password:
      type: string
      length: 255
      nullable: true # for OAuth-created accounts
    display_name:
      type: string
      length: 255
      nullable: true
    gravatar_hash:
      type: string
      length: 32
      nullable: true
    language:
      type: string
      length: 10
      nullable: true
    role:
      type: string
      length: 100
    twitch_oauth:
      type: string
      length: 255
      nullable: true
    created_at:
      type: datetime
    max_events:
      type: integer
      options: { unsigned: true }

  uniqueConstraints:
    unique_login:
      columns: [ login ]
    unique_twitch:
      columns: [ twitch_oauth ]

  oneToMany:
    teams:
      targetEntity: horaro\Library\Entity\UserTeamRelation
      mappedBy: user
    events:
      targetEntity: horaro\Library\Entity\Event
      mappedBy: user

horaro\Library\Entity\Team:
  type: entity
  table: teams

  id:
    id:
      type: integer
      options: { unsigned: true }
      generator: { strategy: AUTO }

  fields:
    name:
      type: string
      length: 255
    slug:
      type: string
      length: 255

  uniqueConstraints:
    unique_slug:
      columns: [ slug ]

  oneToMany:
    users:
      targetEntity: horaro\Library\Entity\UserTeamRelation
      mappedBy: team
      orderBy: { login: ASC }
    events:
      targetEntity: horaro\Library\Entity\Event
      mappedBy: team
      orderBy: { name: ASC }

horaro\Library\Entity\UserTeamRelation:
  type: entity
  table: users_teams

  id:
    user_id:
      type: integer
      options: { unsigned: true }
    team_id:
      type: integer
      options: { unsigned: true }

  fields:
    role:
      type: string
      length: 100

  manyToOne:
    user:
      targetEntity: horaro\Library\Entity\User
      inversedBy: teams
      joinColumn:
        name: user_id
        referencedColumnName: id
        nullable: false
        onDelete: CASCADE
    team:
      targetEntity: horaro\Library\Entity\User
      inversedBy: users
      joinColumn:
        name: team_id
        referencedColumnName: id
        nullable: false
        onDelete: CASCADE

horaro\Library\Entity\Event:
  type: entity
  table: events
  repositoryClass: horaro\Library\Repository\EventRepository

  id:
    id:
      type: integer
      options: { unsigned: true }
      generator: { strategy: AUTO }

  fields:
    name:
      type: string
      length: 255
    slug:
      type: string
      length: 255
    website:
      type: string
      length: 255
      nullable: true
    twitter:
      type: string
      length: 255
      nullable: true
    twitch:
      type: string
      length: 255
      nullable: true
    theme:
      type: string
      length: 100
    secret:
      type: string
      length: 20
      nullable: true
    description:
      type: text
      nullable: true
    max_schedules:
      type: integer
      options: { unsigned: true }

  oneToMany:
    schedules:
      targetEntity: horaro\Library\Entity\Schedule
      mappedBy: event
      orderBy: { name: ASC }

  manyToOne:
    user:
      targetEntity: horaro\Library\Entity\User
      inversedBy: events
      joinColumn:
        name: user_id
        referencedColumnName: id
        nullable: true
        onDelete: CASCADE
    team:
      targetEntity: horaro\Library\Entity\Team
      inversedBy: events
      joinColumn:
        name: team_id
        referencedColumnName: id
        nullable: true
        onDelete: CASCADE

horaro\Library\Entity\Schedule:
  type: entity
  table: schedules
  repositoryClass: horaro\Library\Repository\ScheduleRepository

  id:
    id:
      type: integer
      options: { unsigned: true }
      generator: { strategy: AUTO }

  fields:
    name:
      type: string
      length: 255
    slug:
      type: string
      length: 255
    timezone:
      type: string
      length: 100
    start:
      type: datetime
    website:
      type: string
      length: 255
      nullable: true
    twitter:
      type: string
      length: 255
      nullable: true
    twitch:
      type: string
      length: 255
      nullable: true
    theme:
      type: string
      length: 100
    secret:
      type: string
      length: 20
      nullable: true
    description:
      type: text
      nullable: true
    setup_time:
      type: time
      nullable: true
    max_items:
      type: integer
      options: { unsigned: true }
    updated_at:
      type: datetime
    extra:
      type: text
      nullable: true

  uniqueConstraints:
    unique_slug:
      columns: [ event_id, slug ]

  oneToMany:
    items:
      targetEntity: horaro\Library\Entity\ScheduleItem
      mappedBy: schedule
      orderBy: { position: ASC }
    columns:
      targetEntity: horaro\Library\Entity\ScheduleColumn
      mappedBy: schedule
      orderBy: { position: ASC }

  manyToOne:
    event:
      targetEntity: horaro\Library\Entity\Event
      inversedBy: schedules
      joinColumn:
        name: event_id
        referencedColumnName: id
        nullable: false
        onDelete: CASCADE

horaro\Library\Entity\ScheduleItem:
  type: entity
  table: schedule_items
  repositoryClass: horaro\Library\Repository\ScheduleItemRepository

  id:
    id:
      type: integer
      options: { unsigned: true }
      generator: { strategy: AUTO }

  fields:
    position:
      type: integer
      options: { unsigned: true }
    length:
      type: time
    extra:
      type: text

  manyToOne:
    schedule:
      targetEntity: horaro\Library\Entity\Schedule
      inversedBy: items
      joinColumn:
        name: schedule_id
        referencedColumnName: id
        nullable: false
        onDelete: CASCADE

horaro\Library\Entity\ScheduleColumn:
  type: entity
  table: schedule_columns
  repositoryClass: horaro\Library\Repository\ScheduleColumnRepository

  id:
    id:
      type: integer
      options: { unsigned: true }
      generator: { strategy: AUTO }

  fields:
    position:
      type: integer
      options: { unsigned: true }
    name:
      type: string
      length: 255

  manyToOne:
    schedule:
      targetEntity: horaro\Library\Entity\Schedule
      inversedBy: columns
      joinColumn:
        name: schedule_id
        referencedColumnName: id
        nullable: false
        onDelete: CASCADE

# This entity is defined here just so we get a nice CREATE TABLE statement in the schema.sql
# for the Symfony-provided PDO Session Storage adapter.
horaro\Library\Entity\Session:
  type: entity
  table: sessions

  id:
    id:
      type: binary
      length: 128

  fields:
    data:
      type: blob
      length: 65535
    lifetime:
      type: integer
    mtime:
      type: integer
      options: { unsigned: true }
